var $jscomp={scope:{},findInternal:function(a,c,b){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(c.call(b,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){if(b.get||b.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,c,b,d){if(c){b=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in b||(b[e]={});b=b[e]}a=a[a.length-1];d=b[a];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6-impl","es3");var panelstatus=!0,slider=$(".bxslider").bxSlider({controls:!1,auto:!0,onSlideAfter:function(){autostartslider()}});$(".bxslider2").bxSlider({controls:!1,auto:!0,mode:"fade"});$(".bxslider3").bxSlider({controls:!1,auto:!0,mode:"fade"});$(".bxslider4").bxSlider({controls:!1,auto:!0,mode:"fade"});function autostartslider(){slider.startAuto()}
var timer=setInterval("change()",5E3);$("body").on("load",change());function change(){count=(new Date).getSeconds()%3;images=$(".bxslider5 a");for(i=0;i<images.length;i++)images.eq(i).hide(),Math.round(i%3)==count&&images.eq(i).show("slow")}
$(".btnclose").click(function(){1==panelstatus?($(".prizeinfo").animate({height:"41px"},700,function(){$(".btnclose").css("background-position","0 104px")}),panelstatus=!1):($(".prizeinfo").animate({height:"360px"},700,function(){$(".btnclose").css("background-position","0 0")}),panelstatus=!0)});$(".promobanner").click(function(){var a=$(this).parent().find(".contentbody");"block"==$(a).css("display")?$(a).fadeOut(500):$(a).fadeIn(500)});
$(".contentbody").each(function(a,c){0==a?$(this).css("display","block"):$(this).css("display","none")});function clearallbox(){$(".itms").css("border","1px solid #999");$(".itms").css("z-index","1");$(".sprite").removeClass("icon1");$(".sprite").removeClass("icon2");$(".sprite").removeClass("icon3");$(".sprite").removeClass("icon4");$(".sprite").removeClass("icon5");$(".sprite").removeClass("icon6");$(".itms").css("color","#666");$(".col2").css("display","none")}
$(".itms").click(function(){clearallbox();$(this).css("border","1px solid #1f5fb2");$(this).css("border-right","1px solid #fff");$(this).css("z-index","9");$(this).css("color","#1f5fb2");var a=$(this).index()+1;$("#content"+a).css("display","block");$(this).find(".sprite").addClass("icon"+a)});$(".wechat").hover(function(){$(".wechatqr").stop(!0,!0).fadeIn(500)},function(){$(".wechatqr").stop(!0,!0).fadeOut(200)});
$(".download").hover(function(){$(".downloadqr").stop(!0,!0).fadeIn(500)},function(){$(".downloadqr").stop(!0,!0).fadeOut(200)});function scrolltop(){$(window).scrollTop(0)}function socialpanel(){0==$(window).scrollTop()?$(".scrolltop").css("display","none"):$(".scrolltop").css("display","block")}socialpanel();
function tick(){$("#ticker1 li:first").slideUp(function(){$(this).appendTo($("#ticker1")).slideDown()});$("#ticker2 li:first").slideUp(function(){$(this).appendTo($("#ticker2")).slideDown()})}setInterval(function(){tick()},4E3);var animationtime=1700,animationspd=50,timerend=animationtime/50,timer1=0,timer2=0,timer3=0,barwidth=200;function countUp1(){var a=stat1*animationspd/animationtime*timer1,a=Math.floor(a);$("#count1").text(a);timer1==timerend?clearInterval(stat1_ani):timer1+=1}
function converTime(a){var c=a%60;ret="";ret+=""+~~(a/60)+"&lsquo;"+(10>c?"0":"");return ret+=""+c}function countUp2(){var a=stat2*animationspd/animationtime*timer2,a=Math.floor(a),a=converTime(a);$("#count2").html(a);timer2==timerend?clearInterval(stat2_ani):timer2+=1}function countUp3(){var a=stat3*animationspd/animationtime*timer3,a=Math.floor(a);$("#count3").text(a);timer3==timerend?clearInterval(stat3_ani):timer3+=1}
function progressbar1(){var a=statprogress1/100*barwidth;$("#bar1").animate({right:"-="+a},animationtime)}function progressbar2(){var a=statprogress2/100*barwidth;$("#bar2").animate({right:"-="+a},animationtime)}var stat1_ani,stat2_ani,stat3_ani,bodyheight=$("body").height(),scrollY=$(window).height();$(window).resize(function(){scrollY=$(window).height()});var runonce1=!0,runonce2=!0,runonce3=!0;
$(window).scroll(function(a){socialpanel();a=$(window).scrollTop()+scrollY;1450<a&&1==runonce1&&(stat1_ani=setInterval(function(){countUp1()},animationspd),progressbar1(),runonce1=!1);1550<a&&1==runonce2&&(stat2_ani=setInterval(function(){countUp2()},animationspd),progressbar2(),runonce2=!1);1650<a&&1==runonce3&&(stat3_ani=setInterval(function(){countUp3()},animationspd),runonce3=!1)});
