$(function(){
	//--
	$('.topNotice').find('li').fadeTo(10,0.8);
	$('.topNotice').find('em').fadeTo(10,0.8);
	//--
	$('.footNav').find('li').find('.content:last').css('background','none');
	$('.dividend').find('.btnDiv').find('a:last').css('border','0px');
	//--
	$('.tabContentDiv').find('.tabContent:first').show();
	$('.tab').each(function(i){
		$(this).find('li').each(function(ii){
			$(this).click(
			function(){
				$('.tab').eq(i).find('li').removeClass('liNow');
				$(this).addClass('liNow');
				$('.tabContentDiv').eq(i).find('.tabContent').hide();
				$('.tabContentDiv').eq(i).find('.tabContent').eq(ii).show();
				if($('.sideTab').length>0){
				$('.sideTab').attr('class','tab sideTab');
				$('.sideTab').addClass('sideTab_'+ii);
				}
				}	
				)
			})
		})
	//--
	var sideTZnow=new Array();
	for(i=0;i<50;i++){
	  sideTZnow[i]=0;
	}
	$('.sideTZ').each(function(ii){
	$(this).find('li').each(function(i){
		$(this).find('h1').click(function(){
			if(sideTZnow[ii]==i){
				sideTZnow[ii]=100;
				$('.sideTZ').eq(ii).find('li').find('dl').hide();
				}else{
					sideTZnow[ii]=i;
					$('.sideTZ').eq(ii).find('li').find('dl').hide();
					$('.sideTZ').eq(ii).find('li').eq(i).find('dl').show();
					}
			})
		})
	})		
	//--
	$('.message').find('li').hover(
	   function(){
		   $(this).addClass('liNow');
		   },
	   function(){
		   $(this).removeClass('liNow');
		   }
	)
	//--
	$('.dividend').find('th:last').css('border-right','0px');
	$('.dividend').find('tr').find('td:last').css('border-right','0px');
	//--
	$('.activity').find('li').toggle(
	   function(){
		   $(this).find('.img').slideUp();
		   $(this).find('.imgDiv').slideDown();
		   },
	   function(){
		   $(this).find('.img').slideDown();
		   $(this).find('.imgDiv').slideUp();
		   }
	)
	//
	})