TYPE=VIEW
query=select `3dy1_db`.`c_bet`.`id` AS `id`,`3dy1_db`.`c_bet`.`did` AS `did`,`3dy1_db`.`c_bet`.`uid` AS `uid`,`3dy1_db`.`c_bet`.`username` AS `username`,`3dy1_db`.`c_bet`.`addtime` AS `addtime`,`3dy1_db`.`c_bet`.`type` AS `type`,`3dy1_db`.`c_bet`.`qishu` AS `qishu`,`3dy1_db`.`c_bet`.`mingxi_1` AS `mingxi_1`,`3dy1_db`.`c_bet`.`mingxi_2` AS `mingxi_2`,`3dy1_db`.`c_bet`.`odds` AS `odds`,`3dy1_db`.`c_bet`.`money` AS `money`,`3dy1_db`.`c_bet`.`win` AS `win`,`3dy1_db`.`c_bet`.`js` AS `js`,`3dy1_db`.`c_bet`.`bet_date` AS `bet_date`,`3dy1_db`.`c_bet`.`jieguo` AS `jieguo`,`3dy1_db`.`c_bet`.`fs` AS `fs`,`3dy1_db`.`c_bet`.`dbje` AS `dbje`,`3dy1_db`.`c_bet`.`sm` AS `sm`,`3dy1_db`.`c_bet`.`jkzt` AS `jkzt`,`3dy1_db`.`k_user`.`money` AS `money2`,`3dy1_db`.`k_user`.`is_daili` AS `is_daili`,`3dy1_db`.`k_user`.`dltype` AS `dltype`,`3dy1_db`.`k_user`.`fdjishu` AS `fdjishu`,`3dy1_db`.`k_user`.`fandian` AS `fandian`,`3dy1_db`.`k_user`.`top_uid` AS `top_uid`,`3dy1_db`.`k_user`.`parents` AS `parents`,`3dy1_db`.`k_user`.`guest` AS `guest`,`3dy1_db`.`k_user`.`fxdltype` AS `fxdltype` from (`3dy1_db`.`c_bet` join `3dy1_db`.`k_user`) where (`3dy1_db`.`c_bet`.`uid` = `3dy1_db`.`k_user`.`uid`)
md5=68083e80514aba321ad599ee7a61c682
updatable=1
algorithm=0
definer_user=root
definer_host=%
suid=1
with_check_option=0
timestamp=2017-07-21 10:03:50
create-version=1
source=select `c_bet`.`id` AS `id`,`c_bet`.`did` AS `did`,`c_bet`.`uid` AS `uid`,`c_bet`.`username` AS `username`,`c_bet`.`addtime` AS `addtime`,`c_bet`.`type` AS `type`,`c_bet`.`qishu` AS `qishu`,`c_bet`.`mingxi_1` AS `mingxi_1`,`c_bet`.`mingxi_2` AS `mingxi_2`,`c_bet`.`odds` AS `odds`,`c_bet`.`money` AS `money`,`c_bet`.`win` AS `win`,`c_bet`.`js` AS `js`,`c_bet`.`bet_date` AS `bet_date`,`c_bet`.`jieguo` AS `jieguo`,`c_bet`.`fs` AS `fs`,`c_bet`.`dbje` AS `dbje`,`c_bet`.`sm` AS `sm`,`c_bet`.`jkzt` AS `jkzt`,`k_user`.`money` AS `money2`,`k_user`.`is_daili` AS `is_daili`,`k_user`.`dltype` AS `dltype`,`k_user`.`fdjishu` AS `fdjishu`,`k_user`.`fandian` AS `fandian`,`k_user`.`top_uid` AS `top_uid`,`k_user`.`parents` AS `parents`,`k_user`.`guest` AS `guest`,`k_user`.`fxdltype` AS `fxdltype` from (`c_bet` join `k_user`) where (`c_bet`.`uid` = `k_user`.`uid`)
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `3dy1_db`.`c_bet`.`id` AS `id`,`3dy1_db`.`c_bet`.`did` AS `did`,`3dy1_db`.`c_bet`.`uid` AS `uid`,`3dy1_db`.`c_bet`.`username` AS `username`,`3dy1_db`.`c_bet`.`addtime` AS `addtime`,`3dy1_db`.`c_bet`.`type` AS `type`,`3dy1_db`.`c_bet`.`qishu` AS `qishu`,`3dy1_db`.`c_bet`.`mingxi_1` AS `mingxi_1`,`3dy1_db`.`c_bet`.`mingxi_2` AS `mingxi_2`,`3dy1_db`.`c_bet`.`odds` AS `odds`,`3dy1_db`.`c_bet`.`money` AS `money`,`3dy1_db`.`c_bet`.`win` AS `win`,`3dy1_db`.`c_bet`.`js` AS `js`,`3dy1_db`.`c_bet`.`bet_date` AS `bet_date`,`3dy1_db`.`c_bet`.`jieguo` AS `jieguo`,`3dy1_db`.`c_bet`.`fs` AS `fs`,`3dy1_db`.`c_bet`.`dbje` AS `dbje`,`3dy1_db`.`c_bet`.`sm` AS `sm`,`3dy1_db`.`c_bet`.`jkzt` AS `jkzt`,`3dy1_db`.`k_user`.`money` AS `money2`,`3dy1_db`.`k_user`.`is_daili` AS `is_daili`,`3dy1_db`.`k_user`.`dltype` AS `dltype`,`3dy1_db`.`k_user`.`fdjishu` AS `fdjishu`,`3dy1_db`.`k_user`.`fandian` AS `fandian`,`3dy1_db`.`k_user`.`top_uid` AS `top_uid`,`3dy1_db`.`k_user`.`parents` AS `parents`,`3dy1_db`.`k_user`.`guest` AS `guest`,`3dy1_db`.`k_user`.`fxdltype` AS `fxdltype` from (`3dy1_db`.`c_bet` join `3dy1_db`.`k_user`) where (`3dy1_db`.`c_bet`.`uid` = `3dy1_db`.`k_user`.`uid`)
