TYPE=VIEW
query=select `3dy1_db`.`k_money`.`m_id` AS `m_id`,`3dy1_db`.`k_money`.`uid` AS `uid`,substring_index(`3dy1_db`.`k_money`.`m_order`,\'_\',1) AS `tzname`,`3dy1_db`.`k_money`.`m_value` AS `m_value`,`3dy1_db`.`k_money`.`m_order` AS `m_order`,`3dy1_db`.`k_money`.`status` AS `status`,`3dy1_db`.`k_money`.`m_make_time` AS `m_make_time`,`3dy1_db`.`k_money`.`about` AS `about`,`3dy1_db`.`k_money`.`update_time` AS `update_time`,`3dy1_db`.`k_money`.`pay_card` AS `pay_card`,`3dy1_db`.`k_money`.`pay_num` AS `pay_num`,`3dy1_db`.`k_money`.`pay_address` AS `pay_address`,`3dy1_db`.`k_money`.`type` AS `type`,`3dy1_db`.`k_money`.`pay_name` AS `pay_name`,`3dy1_db`.`k_money`.`sxf` AS `sxf`,`3dy1_db`.`k_money`.`jifen` AS `jifen`,`3dy1_db`.`k_money`.`assets` AS `assets`,`3dy1_db`.`k_money`.`balance` AS `balance`,`3dy1_db`.`k_user`.`username` AS `username`,`3dy1_db`.`k_user`.`is_daili` AS `is_daili`,`3dy1_db`.`k_user`.`dltype` AS `dltype`,`3dy1_db`.`k_user`.`fandian` AS `fandian`,`3dy1_db`.`k_user`.`fdjishu` AS `fdjishu`,`3dy1_db`.`k_user`.`parents` AS `parents`,`3dy1_db`.`k_user`.`top_uid` AS `top_uid`,`3dy1_db`.`k_user`.`guest` AS `guest`,`3dy1_db`.`k_user`.`fxdltype` AS `fxdltype`,`3dy1_db`.`k_user`.`money` AS `money` from (`3dy1_db`.`k_money` join `3dy1_db`.`k_user`) where ((`3dy1_db`.`k_money`.`uid` = `3dy1_db`.`k_user`.`uid`) and (`3dy1_db`.`k_money`.`type` = 200)) order by `3dy1_db`.`k_money`.`m_id` desc
md5=fe7e36496824400060df7c46f938ad39
updatable=1
algorithm=0
definer_user=root
definer_host=%
suid=1
with_check_option=0
timestamp=2017-07-21 10:03:50
create-version=1
source=select `k_money`.`m_id` AS `m_id`,`k_money`.`uid` AS `uid`,substring_index(`k_money`.`m_order`,\'_\',1) AS `tzname`,`k_money`.`m_value` AS `m_value`,`k_money`.`m_order` AS `m_order`,`k_money`.`status` AS `status`,`k_money`.`m_make_time` AS `m_make_time`,`k_money`.`about` AS `about`,`k_money`.`update_time` AS `update_time`,`k_money`.`pay_card` AS `pay_card`,`k_money`.`pay_num` AS `pay_num`,`k_money`.`pay_address` AS `pay_address`,`k_money`.`type` AS `type`,`k_money`.`pay_name` AS `pay_name`,`k_money`.`sxf` AS `sxf`,`k_money`.`jifen` AS `jifen`,`k_money`.`assets` AS `assets`,`k_money`.`balance` AS `balance`,`k_user`.`username` AS `username`,`k_user`.`is_daili` AS `is_daili`,`k_user`.`dltype` AS `dltype`,`k_user`.`fandian` AS `fandian`,`k_user`.`fdjishu` AS `fdjishu`,`k_user`.`parents` AS `parents`,`k_user`.`top_uid` AS `top_uid`,`k_user`.`guest` AS `guest`,`k_user`.`fxdltype` AS `fxdltype`,`k_user`.`money` AS `money` from (`k_money` join `k_user`) where ((`k_money`.`uid` = `k_user`.`uid`) and (`k_money`.`type` = 200)) order by `k_money`.`m_id` desc
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `3dy1_db`.`k_money`.`m_id` AS `m_id`,`3dy1_db`.`k_money`.`uid` AS `uid`,substring_index(`3dy1_db`.`k_money`.`m_order`,\'_\',1) AS `tzname`,`3dy1_db`.`k_money`.`m_value` AS `m_value`,`3dy1_db`.`k_money`.`m_order` AS `m_order`,`3dy1_db`.`k_money`.`status` AS `status`,`3dy1_db`.`k_money`.`m_make_time` AS `m_make_time`,`3dy1_db`.`k_money`.`about` AS `about`,`3dy1_db`.`k_money`.`update_time` AS `update_time`,`3dy1_db`.`k_money`.`pay_card` AS `pay_card`,`3dy1_db`.`k_money`.`pay_num` AS `pay_num`,`3dy1_db`.`k_money`.`pay_address` AS `pay_address`,`3dy1_db`.`k_money`.`type` AS `type`,`3dy1_db`.`k_money`.`pay_name` AS `pay_name`,`3dy1_db`.`k_money`.`sxf` AS `sxf`,`3dy1_db`.`k_money`.`jifen` AS `jifen`,`3dy1_db`.`k_money`.`assets` AS `assets`,`3dy1_db`.`k_money`.`balance` AS `balance`,`3dy1_db`.`k_user`.`username` AS `username`,`3dy1_db`.`k_user`.`is_daili` AS `is_daili`,`3dy1_db`.`k_user`.`dltype` AS `dltype`,`3dy1_db`.`k_user`.`fandian` AS `fandian`,`3dy1_db`.`k_user`.`fdjishu` AS `fdjishu`,`3dy1_db`.`k_user`.`parents` AS `parents`,`3dy1_db`.`k_user`.`top_uid` AS `top_uid`,`3dy1_db`.`k_user`.`guest` AS `guest`,`3dy1_db`.`k_user`.`fxdltype` AS `fxdltype`,`3dy1_db`.`k_user`.`money` AS `money` from (`3dy1_db`.`k_money` join `3dy1_db`.`k_user`) where ((`3dy1_db`.`k_money`.`uid` = `3dy1_db`.`k_user`.`uid`) and (`3dy1_db`.`k_money`.`type` = 200)) order by `3dy1_db`.`k_money`.`m_id` desc
